elementary/wingpanel-indicator-network

- src/common/Widgets/NMVisualizer.vala
A bad merge caused the networks to no longer be prioritized according to the connection state.
#26
> Fixed network state prioritization regression [#26]

- src/common/Widgets/NMVisualizer.vala
When using VirtualBox virtual machines with host-only adapters configured, extra network interfaces are created on the host machine. These are picked up by the network indicator.
There's little point showing them there, so this branch proposes not adding them to the indicator.
> Hide VirtualBox host-only adapters from indicator

- src/common/Widgets/NMVisualizer.vala
Previously, when new network interfaces were added/removed, we weren't doing the check to determine whether we needed to select a new icon for the panel.
This sometimes resulted in a suboptimal icon being selected when wingpanel first loads and probably caused some issues when added and removing pluggable network devices.
> Update network state on addition/removal of network interfaces

- src/Widgets/ModemInterface.vala
Only allow the toggle switch to change the state of the device when it's in a valid state. This doesn't affect the behavior of the indicator at all, it just fixes the indicator and the switchboard plug fighting each other.
> Improve cellular switch logic

- src/Indicator.vala
- src/Widgets/DisplayWidget.vala
- src/Widgets/ModemInterface.vala
- src/common/Widgets/NMVisualizer.vala
- src/common/Widgets/WidgetNMInterface.vala
Fixes #5 
Looks like the following:
I believe the vertical alignment issue is caused by https://github.com/elementary/icons/issues/351
This has been tested with the large text setting and doesn't break things any more than any of the other large text in the panel.
> Display network type next to cellular indicator

- src/Indicator.vala
In Juno, the command to run the captive portal has changed to `io.elementary.capnet-assist`. This updates said command on the indicator to bring back the portal
> Juno: Update capnet-assist command

- src/Widgets/PopoverWidget.vala
- src/common/Widgets/WidgetNMInterface.vala
Fixes #69.
Turns out that the separator was initialized lately in the process of creating an UI for a device which caused some interfaces like VpnInterface fail to update the visibility of a separator because it wasn't yet initialized. I made `is_dm` method static, because I thought it would be bitesize here.
> Fix double separators

- CMakeLists.txt
- config.vala.cmake
- src/CMakeLists.txt
None of these constants are used
> Remove unused config.vala

- src/Indicator.vala
This branch is needed if https://github.com/elementary/wingpanel/pull/103 were to get merged, as everything that has to do with reading the network state depends on the popover widget being initialized...
Yes, i'm the first to admit that it's ugly having to initialize everything from the constructor, but sadly the whole logic with the network indicator is tightly dependent on the DisplayWidget :sad-dog:
> Initialize everything on Indicator creation

- src/Indicator.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/WifiInterface.vala
Fixes #70 
I don't know if we should look at finding a good place to put a spinner in there, because it takes a second or two to go from showing just the one AP you're connected to, to showing the full list after opening the indicator. But I'll leave that as a UX discussion of how best to display that.
There's already a "scanning for APs" spinner that's shown as a placeholder when there's nothing in the listbox, but we always have the current AP in there in this case.
> Scan for APs on open indicator

- src/common/Widgets/WifiMenuItem.vala
Fixes an issue where sometimes the active item isn't styled correctly
> WifiMenuitem: move css_name to construct

- src/Widgets/WifiInterface.vala
I just think it looks nicer aligned like the other menu items instead of centered
> WifiInterface: justify scanning placeholder

- src/Indicator.vala
- src/Widgets/EtherInterface.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/WifiInterface.vala
> Add tooltip indicator

- src/Widgets/ModemInterface.vala
- src/Widgets/PopoverWidget.vala
- src/common/Widgets/WidgetNMInterface.vala
This property is only ever set in ModemInterface so it doesn't need to be a part of Network.WidgetNMInterface
> Move extra_info to ModemInterface

- src/Indicator.vala
This PR is to fix the indicator tooltip which shows "Disconnected" when I first boot up and the greeter starts even though my wifi is connected.
> Fix tooltip showing stale disconnected label on first boot

- src/Indicator.vala
- src/Widgets/PopoverWidget.vala
Fixes #6 
Fixes #8 
Needs input on:
- position of airplane mode switch
- whether the switch should be available in the greeter as well as in the session
> Add airplane mode switch to popover; add middle-click tooltip

- src/Widgets/EtherInterface.vala
- src/Widgets/ModemInterface.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/VpnInterface.vala
- src/Widgets/WifiInterface.vala
- src/common/Widgets/WidgetNMInterface.vala
Network Manager has a built-in function for disambiguating device names, so let's use that instead of reinventing the wheel
> Use disambiguate_names from NM

- src/Widgets/WifiInterface.vala
- src/common/Widgets/WifiMenuItem.vala
Towards eventually removing `Network.State` like we did in Switchboard since NM provides state enums already
> WifiInterface: use NM.DeviceState

- src/Widgets/WifiInterface.vala
- src/Widgets/WifiMenuItem.vala
Reverts elementary/wingpanel-indicator-network#275
This seems to have introduced some weird behavior where the menuitem is reactivated in a loop forever
> Revert "WifiMenuItem: use built-in activate signal"

- src/Widgets/DisplayWidget.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/VpnInterface.vala
- src/Widgets/VpnMenuItem.vala
- src/Widgets/WifiMenuItem.vala
This MR comes as a complementary work of https://github.com/elementary/switchboard-plug-network/pull/338 to make wireguard connections first class citizens alongside more classical VPN.
Warning, in order to build this, you need an up-to-date version of libnm (myself I have 1.32.12 installed). The packaged libnm.vapi is outdated, that’s why I take the liberty to remove it from this repository. Even after removing it, the project build just fine.
This MR fixes #245
> List Wireguard connection as possible VPN

- src/Widgets/DisplayWidget.vala
* Bump copyright header
* Subclass box
* Set pixel_size since `Gtk.IconSize.LARGE_TOOLBAR` will go away
* Use child property in revealer
* code style
> DisplayWidget: gtk4 prep

- data/Indicator.css
- src/Indicator.vala
- src/Widgets/EtherInterface.vala
- src/Widgets/ModemInterface.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/VpnMenuItem.vala
Adding a provider to a style context is deprecated. Uses the same styles from Quick Settings. Toggles are now round-rects
> Add styles to screen

- src/Widgets/PopoverWidget.vala
* Bump copyright header
* Subclass Box not Grid since we append widgets, not attach
* Use child property for Revealer and FlowBoxChild
> PopoverWidget: GTK4 prep

- src/Widgets/WifiInterface.vala
* Bump copyright header
* Grid → Box
* Child property for Revealer and ScrolledWindow
* No more `dialog.run` so use `present` and destroy in `response`
> WifiInterface: GTK4 prep

- README.md
- meson.build
We now use `GLib.ListStore.n_items` since #326:
```diff
private void check_vpn_availability () {
-        show_vpn (vpn_list.get_child_at_index (0) != null);
+        show_vpn (vpn_list.n_items > 0);
}
```
This is available on gio-2.0 >= 2.74 as written in [Valadoc](https://valadoc.org/gio-2.0/GLib.ListStore.n_items.html), so make sure to require it. Also explicit that we require libnm-dev >= 1.24 in README
---
I noticed this because the daily recipe of wingpanel-indicator-network fails in Jammy:
https://code.launchpad.net/~elementary-os/+archive/ubuntu/daily/+build/30646060
```
../src/Widgets/VpnInterface.vala:57.19-57.34: error: `GLib.ListStore.n_items' is not available in gio-2.0 2.72.4. Use gio-2.0 >= 2.74
57 |         show_vpn (vpn_list.n_items > 0);
| …
```
> meson: Require gio-2.0 >= 2.74

- data/Indicator.css
- meson.build
- src/Indicator.vala
- src/Widgets/EtherInterface.vala
- src/Widgets/PopoverWidget.vala
- src/Widgets/SettingsToggle.vala
- src/Widgets/VpnMenuItem.vala
Can be rebase merged
Creates a SettingsToggle widget like we did in Quick Settings. This should eventually be moved into Wingpanel, but kind of prototyping in indicators first to make sure it covers all the cases before proposing to the library. Couple things different here from the one in Quick Settings:
* Not a `FlowBoxChild`. We're using FlowBox now, but we might want to use GridView later or a box or something else. Just future proofing ourselves
* All properties are `set` and none `construct`. This is in case we want to create these widgets from a model like in GridView where we recycle widgets.
* Use `action-name` instead of `active`. Avoids some jank. This is the recommended way to handle ToggleButtons in GTK and it means we can set disabled states more cleanly etc
> Create SettingsToggle widget

- src/Widgets/WifiMenuItem.vala
No button release event in GTK4. Probably long term this should use an action, but this is the simplest solution
> WifiMenuItem: button_release_event → notify active

- src/Widgets/WifiInterface.vala
Can't subclass Gtk.Label in GTK4. Add a FIXME line since this would be a good usage of Granite.Placeholder in the GTK4 port
> Wifiinterface: Don't subclass Gtk.Label

- data/network.metainfo.xml.in
Bump to 8 because we stopped building for Jammy
> Metainfo: add 8.0.0 release notes

- src/Indicator.vala
- src/Widgets/PopoverWidget.vala
- src/rfkill.vala
This changes Airplane Mode so that it uses RFKill to disable _radios_, not disable all _networking_. This means Airplane mode correctly disables wifi and cellular, but not wired networking
Partially fixes #45. The toggle is now correct but the indicator is not
> AirplaneMode: use RFKill

- src/rfkill.vala
Make sure we don't turn bluetooth back on if it was software disabled, only if it was hardware locked by an airplane key
> Check bluetooth for hardware lock before enabling

- src/Widgets/PopoverWidget.vala
Crash introduced in https://github.com/elementary/wingpanel-indicator-network/pull/338 causes wingpanel to not appear in greeter.
Only removed the `is_in_session` check so airplane toggle also shows up in greeter.
> Fix crash in greeter
