elementary/wingpanel-indicator-network

debian/control
Fixes build failure introduced by #57
=> Update packaging deps

src/Widgets/EtherInterface.vala, src/Widgets/ModemInterface.vala, src/Widgets/VpnInterface.vala, src/Widgets/WifiInterface.vala, src/common/Widgets/AbstractWifiInterface.vala
* No more warnings
* Teeny tiny bit of code style/copyright header cleanup in the process
=> Use explicit async .begin statements

src/Widgets/PopoverWidget.vala
There's a built-in Gtk widget for this, no need for a custom widget
=> Use Gtk.ModelButton

src/Widgets/DisplayWidget.vala
=> Use margin-start instead of margin-left

src/Widgets/VpnInterface.vala
=> Catch error when deactivating VPN

.travis.yml, src/Widgets/EtherInterface.vala, src/Widgets/ModemInterface.vala, src/Widgets/VpnInterface.vala, src/Widgets/WifiInterface.vala, src/common/Widgets/AbstractVpnInterface.vala
This isn't building because Travis doesn't build against the latest wingpanel
=> Update for wingpanel deprecations

src/Widgets/WifiInterface.vala
=> Remove close button from hidden network dialog

src/Widgets/EtherInterface.vala
Fixes #71 
Seems like the autoconnect stuff just doesn't work anymore. The plug has a different (working) way of activating the connection, so change this to match.
=> Change indicator ethernet connection code to match plug

src/common/Widgets/AbstractWifiInterface.vala
Only trivial changes from #105, plus some other code style cleanups
=> AbstractWifiInterface: Code style cleanup

src/Widgets/DisplayWidget.vala
=> DisplayWidget: Set wireless-offline for failed wifi connection

src/common/Widgets/AbstractEtherInterface.vala, src/common/Widgets/WidgetNMInterface.vala, src/common/Widgets/WifiMenuItem.vala, vapi/libnm.vapi, vapi/libnma.vapi
A [strictly whitespace](https://github.com/elementary/wingpanel-indicator-network/pull/117/files?w=1) change to use four spaces everywhere instead of tabs.
=> Tabs → Spaces

src/common/Widgets/WifiMenuItem.vala
One of the improvements from #105
=> WifiMenuItem: rewrite fetching the symbolic strength icon

src/Widgets/WifiInterface.vala
=> Fix Wingpanel icon appears in the dock when showing hidden_dialog

src/common/Widgets/AbstractModemInterface.vala
=> AbstractModemInterface: Bump copyright header

src/Widgets/WifiInterface.vala
* Bump copyright
* Explicit scope
* code style
=> WifiInterface: misc cleanup

src/common/Widgets/AbstractVpnInterface.vala
- Object initialize refactor 
- Bump copyright header
=> AbstractVpnInterface : misc cleanup

src/Widgets/DisplayWidget.vala
* Bump copyright headerr
* Explicit variable scope
* Subclass Grid instead of Box
* Code style
=> DisplayWidget: misc cleanup

src/Widgets/WifiInterface.vala
* Bool doesn't do anything
* Class instead of a method
=> WifiInterface: make PlaceholderLabel a private class

src/common/Widgets/WifiMenuItem.vala
Matches the logic and strings used in the switchboard plug
=> WifiMenuItem: Improve encryption detection

src/common/Widgets/WifiMenuItem.vala
* Remove todo as this appears to be working as intended
* Use latest code style
* Shorter tooltip text
=> WifiMenuItem: Update error tooltip text

src/Widgets/EtherInterface.vala, src/Widgets/ModemInterface.vala, src/Widgets/PopoverWidget.vala, src/Widgets/VpnInterface.vala, src/Widgets/WifiInterface.vala, src/common/Widgets/WidgetNMInterface.vala
As title implies. Tested for ethernet and WiFi but can't test modem and VPN but I doubt it would be an issue.
=> Use Granite.SwitchModelButton and Gtk.Separator

data/network.appdata.xml.in, src/Widgets/VpnInterface.vala
=> Fixed an issue with a blank line in the VPN list in the indicator

src/Widgets/VpnInterface.vala, src/common/Widgets/VpnMenuItem.vala
Also refactor the code a bit to make it simpler.
=> VpnMenuItem: Avoid to call method of a possibly null connection object

meson.build, src/Widgets/WifiInterface.vala, src/common/Widgets/WifiMenuItem.vala, vapi/libnm.vapi
=> Show WPA3 protected wifi connection status if any

data/network.appdata.xml.in, src/Widgets/PopoverWidget.vala
=> PopoverWidget: list VPNs above wifi

data/Indicator.css, data/network-vpn-acquiring-symbolic.svg, data/network-vpn-connected-symbolic.svg, data/network-vpn-disconnected-symbolic.svg, data/network-vpn-error-symbolic.svg, data/network.appdata.xml.in, data/network.gresource.xml, src/Indicator.vala, src/Utils.vala, src/Widgets/PopoverWidget.vala, src/Widgets/VpnInterface.vala, src/Widgets/VpnMenuItem.vala
=> Show VPN as a FlowBox of ToggleButtons

data/network.metainfo.xml.in, meson.build, src/Indicator.vala, src/Widgets/PopoverWidget.vala
=> Use dbus_call for setting airplane mode

data/network.metainfo.xml.in, src/Widgets/VpnInterface.vala, src/Widgets/VpnMenuItem.vala
=> VpnInterface: catch errors in activate_cb

meson.build
Contains a critical fix for airplane mode and a highly visible and reproducible VPN fix
=> Release 7.0.1

src/Widgets/WifiInterface.vala
This is an oversight from #276
=> WifiInterface: avoid infinite recursive update

data/Indicator.css
=> Fix focus style

data/network.gresource.xml, data/network.metainfo.xml.in
=> Small icons on HiDPI displays

.github/workflows/main.yml, README.md, data/meson.build, data/network.policy.in, meson.build, src/Widgets/WifiInterface.vala
Fixes https://github.com/elementary/greeter/issues/615
=> Allow adding new system connections without admin prompt

src/Widgets/PopoverWidget.vala, src/Widgets/VpnInterface.vala, src/Widgets/WifiInterface.vala
Can't `get_children` in GTK4
Can be rebase merged
=> Replace ListBox and FlowBox iterators for GTK4

src/Widgets/VpnInterface.vala
There's no `add` or `remove` signals in GTK4, so use a model instead and connect to `items_changed`
=> VpnInterface: bind model

src/Widgets/WifiMenuItem.vala
* Bump copyright header
* Use child property for radiobutton
* Set radiobutton group
* Icon size is 16px (menu) by default
* child property for ListBoxRow
=> WifiMenuItem: GTK4 prep
